# Generated by Django 3.2 on 2023-06-05 15:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username=django.db.models.expressions.F('author')), name='no_self_follow'),
        ),
    ]
